### ISSUE TITLE
Theres a problem with the server pack because it doesnt fully start.

### ISSUE THREAD

**Issue by MasterKyle08** [YassaaaTU/ALOE#2]
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true @unix_args.txt
[05:57:33] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.1.54, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[05:57:33] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.2 by Oracle Corporation
[05:57:33] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/container/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
[05:57:36] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing mandatory dependencies: forge
[05:57:59] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[05:58:00] [main/ERROR] [mixin/]: Mixin config mixin.cleancut.json does not specify "minVersion" property
[05:58:01] [main/ERROR] [mixin/]: Mixin config goodall-common.mixins.json does not specify "minVersion" property
[05:58:01] [main/ERROR] [mixin/]: Mixin config goodall.mixins.json does not specify "minVersion" property
[05:58:01] [main/ERROR] [mixin/]: Mixin config myrtrees-common.mixins.json does not specify "minVersion" property
[05:58:02] [main/ERROR] [mixin/]: Mixin config polylib.mixins.json does not specify "minVersion" property
[05:58:02] [main/ERROR] [mixin/]: Mixin config radium.mixins.json does not specify "minVersion" property
[05:58:02] [main/ERROR] [mixin/]: Mixin config radon.mixins.json does not specify "minVersion" property
[05:58:02] [main/ERROR] [mixin/]: Mixin config sprout.mixins.json does not specify "minVersion" property
[05:58:03] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.integral.enigmaticlegacy.MixinConnector]
[05:58:03] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.leobeliik.extremesoundmuffler.MixinConnector]
[05:58:03] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [thelm.jaopca.mixins.JAOPCAMixinConnector]
[05:58:03] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[05:58:03] [main/WARN] [mixin/]: Reference map 'ars_instrumentum.refmap.json' for ars_instrumentum.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:04] [main/WARN] [mixin/]: Reference map 'createdeco.refmap.json' for createdeco.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:04] [main/WARN] [mixin/]: Reference map 'enhanced_mushrooms-refmap.json' for enhanced_mushrooms.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:05] [main/WARN] [mixin/]: Reference map 'everycomp.refmap.json' for everycomp.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:05] [main/WARN] [mixin/]: Reference map 'farmersrespite.refmap.json' for farmersrespite.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:05] [main/WARN] [mixin/]: Reference map 'goodall-forge-refmap.json' for goodall.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:05] [main/WARN] [mixin/]: Reference map 'insanelib.refmap.json' for insanelib.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:06] [main/WARN] [mixin/]: Reference map 'jobsplus.refmap.json' for jobsplus.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:06] [main/WARN] [mixin/]: Reference map 'morevillagers-forge-forge-refmap.json' for morevillagers.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:06] [main/WARN] [mixin/]: Reference map 'myrtrees-common-refmap.json' for myrtrees-common.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:06] [main/WARN] [mixin/]: Reference map 'naturalist-forge-forge-refmap.json' for naturalist.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:06] [main/WARN] [mixin/]: Reference map 'nethersdelight.refmap.json' for nethersdelight.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:06] [main/WARN] [mixin/]: Reference map 'polylib-common-refmap.json' for polylib.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:06] [main/INFO] [Radium/]: Loaded configuration file for Radium: 100 options available, 0 override(s) found
[05:58:07] [main/WARN] [mixin/]: Reference map 'universalgrid.refmap.json' for universalgrid.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:07] [main/WARN] [mixin/]: Reference map 'yungsbridges.refmap.json' for yungsbridges.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:07] [main/WARN] [mixin/]: Reference map 'yungsbridges.refmap.json' for yungsbridges_forge.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:07] [main/WARN] [mixin/]: Reference map 'yungsextras.refmap.json' for yungsextras.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:07] [main/WARN] [mixin/]: Reference map 'yungsextras.refmap.json' for yungsextras_forge.mixins.json could not be read. If this is a development environment you can ignore this message
[05:58:08] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[05:58:08] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/player/LocalPlayer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER)
[05:58:08] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.player.LocalPlayer was not found ars_nouveau.mixins.json:elytra.ClientElytraMixin
[05:58:08] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/screens/inventory/AbstractContainerScreen for invalid dist DEDICATED_SERVER
[05:58:08] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/screens/inventory/AbstractContainerScreen (java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/inventory/AbstractContainerScreen for invalid dist DEDICATED_SERVER)
[05:58:08] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.gui.screens.inventory.AbstractContainerScreen was not found findme-common.mixins.json:MixinSlotRenderer
[05:58:08] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/particle/ParticleEngine for invalid dist DEDICATED_SERVER
[05:58:08] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/particle/ParticleEngine (java.lang.RuntimeException: Attempted to load class net/minecraft/client/particle/ParticleEngine for invalid dist DEDICATED_SERVER)
[05:58:08] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.particle.ParticleEngine was not found findme-common.mixins.json:ParticleEngineAccessor
[05:58:09] [main/WARN] [mixin/]: Error loading class: net/darkhax/darkutils/features/charms/CharmEffects (java.lang.ClassNotFoundException: net.darkhax.darkutils.features.charms.CharmEffects)
[05:58:09] [main/WARN] [mixin/]: Error loading class: com/brandon3055/csg/ModEventHandler (java.lang.ClassNotFoundException: com.brandon3055.csg.ModEventHandler)
[05:58:10] [main/INFO] [Smooth Boot/]: Smooth Boot config initialized
[05:58:11] [main/WARN] [mixin/]: @Inject(@At("HEAD")) Shift.BY=1 on blueprint.mixins.json:EntityMixin::handler$zdj000$baseTick exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[05:58:11] [main/INFO] [mixin/]: Mixing MixinLivingEntity from assets/enigmaticlegacy/enigmaticlegacy.mixins.json into net.minecraft.world.entity.LivingEntity
[05:58:12] [main/INFO] [mixin/]: Mixing MixinPlayer from assets/enigmaticlegacy/enigmaticlegacy.mixins.json into net.minecraft.world.entity.player.Player
[05:58:12] [main/INFO] [mixin/]: Mixing MixinMobEffect from assets/enigmaticlegacy/enigmaticlegacy.mixins.json into net.minecraft.world.effect.MobEffect
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.54/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 7 more
Caused by: java.lang.IllegalAccessError: class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube tried to access method 'void net.minecraft.world.phys.shapes.VoxelShape.<init>(net.minecraft.world.phys.shapes.DiscreteVoxelShape)' (me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube is in module radium@0.7.10 of loader 'TRANSFORMER' @5b000fe6; net.minecraft.world.phys.shapes.VoxelShape is in module minecraft@1.18.2 of loader 'TRANSFORMER' @5b000fe6)
	at TRANSFORMER/radium@0.7.10/me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube.<init>(VoxelShapeSimpleCube.java:31)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_166049_(Shapes.java:1601)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_83048_(Shapes.java:50)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.<clinit>(Shapes.java:26)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.Block.m_49796_(Block.java:138)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.SaplingBlock.<clinit>(SaplingBlock.java:20)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:59)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.m_190634_(CarverConfiguration.java:16)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:12)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:30)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:19)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206400_(BuiltinRegistries.java:45)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206392_(BuiltinRegistries.java:101)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:100)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.<clinit>(Registry.java:633)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Main.main(Main.java:109)
	... 13 more
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true @unix_args.txt
[05:58:21] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.1.54, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[05:58:21] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.2 by Oracle Corporation
[05:58:21] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/container/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
[05:58:24] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing mandatory dependencies: forge

**Comment by YassaaaTU** [comment]
Upgrade your forge version to the same one as the one in the modpack because that's the one that works. 
I also included the same working forge version file in the server pack 

![image](https://user-images.githubusercontent.com/5587106/180728467-3ff2df11-eab7-49b3-94d1-50f2b472ae82.png)
![image](https://user-images.githubusercontent.com/5587106/180727988-8b6e5861-338c-41fe-9f32-039ee190a340.png)
![image](https://user-images.githubusercontent.com/5587106/180728260-b260b7b0-b273-49d3-8d01-8bcc23179114.png)
![image](https://user-images.githubusercontent.com/5587106/180728349-cdfcf592-4617-4ad2-a1ba-013173c8c46c.png)

**Comment by YassaaaTU** [comment]
also please use https://mclo.gs/ or http://crashy.net/ for crash reports or logs
